# 公共配置文件
spring:
  application:
    name: LotusOJ
  # 默认 dev 环境
  profiles:
    active: dev
  #// 代码
private String code;
// 语言
private String language;
// 输入
private String input;r
  # session 配置
  session:
#     todo 取消注释开启分布式 session（须先配置 Redis）
    store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oj_db?characterEncoding=utf8&useSSL=false&rewriteBatchedStatements=true
    username: root
    password: 0721
    type: com.alibaba.druid.pool.DruidDataSource
  # Redis 配置
  # todo 需替换配置，然后取消注释
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000
  # Elasticsearch 配置
  # todo 需替换配置，然后取消注释
#  elasticsearch:
#    uris: http://localhost:9200
#    username: root
#    password: 123456
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
server:// 代码
private String code;
// 语言
private String language;
// 输入
private String input;
// 代码
private String code;
// 语言
private String language;
// 输入
private String input;
// 代码
private String code;
// 语言
private String language;
// 输入
private String input;
// 代码
private String code;
// 语言
private String language;
// 输入
private String input;
// 代码
private String code;
// 语言
private String language;
// 输入
private String input;

  address: 0.0.0.0
  port: 8101
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# 微信相关
wx:
  # 微信公众平台
  # todo 需替换配置
  mp:
    token: xxx
    aesKey: xxx
    appId: xxx
    secret: xxx
    config-storage:
      http-client-type: HttpClient
      key-prefix: wx
      redis:
        host: 127.0.0.1
        port: 6379
      type: Memory
  # 微信开放平台
  # todo 需替换配置
  open:
    appId: xxx
    appSecret: xxx
# 对象存储
# todo 需替换配置
cos:
  client:
    accessKey: xxx
    secretKey: xxx
    region: xxx
    bucket: xxx

knife4j:
  enable: true
  openapi:
    title: 接口文档
    description: "接口测试"
    email: gilgamesh@qq.com
    concat:
    url: https://github.com/fantasy-lotus/
    version: v4.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    group:
      test1:
        group-name:  lotus
        api-rule: package
        api-rule-resources:
          - com.lotus.LOJ.controller